config/routes.rb
Blog::Application.routes.draw do

resources :articles do
  resources :comments
end


end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

http_basic_authenticate_with name: "user", password: "secret", except: [:index, :show]

def index
  @articles = Article.all
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy

  redirect_to articles_path
end

def show
  @article = Article.find(params[:id])
end


def edit
  @article = Article.find(params[:id])
end

def new
  @article = Article.new
end



def update
  @article = Article.find(params[:id])

  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

private
  def article_params
    params.require(:article).permit(:title, :text)
  end




def create
  @article = Article.new(article_params)

  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end

private
  def article_params
    params.require(:article).permit(:title, :text)
  end






end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "user", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h2>Edit article</h2>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<br>
<div style="margin-top:-10px;">
<%= link_to 'New article', new_article_path %>
</div>
<br>

 
<% @articles.each do |article| %>
<hr style="margin-right:20px;">

        <h3><%= article.title %></h3>
        <%= article.text %><br><br>
        <%= link_to 'Show', article_path(article) %> |
        <%= link_to 'Edit', edit_article_path(article) %> |
        <%= link_to 'Destroy', article_path(article),
                        method: :delete, data: { confirm: 'Are you sure?' } %>
                        <br><br>

<% end %>

app/views/articles/new.html.erb
<h2>New article</h2>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
<br><br>
  <strong>Text:</strong>
  <%= @article.text %>

 
<h2 style="margin-left:10px;">Comments:</h2>
<div style="margin-left:16px;">
<% @article.comments.each do |comment| %>
    <hr style="margin-left:-16px;">
    <strong>Commenter:</strong>
     <%= comment.commenter %><br><br>

    <strong>Comment:</strong><br>
    <%= comment.body %><br><br>

    <%= link_to 'Destroy Comment', [comment.article, comment],
                   method: :delete,
                   data: { confirm: 'Are you sure?' } %><br><br>

<% end %>
</div>

<hr>
<h2 style="margin-left:10px;">Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>

    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %><br><br>

    <%= f.label :body %><br>
    <%= f.text_area :body %><br><br>

    <%= f.submit %>

<% end %>
<br>
</p>
<div style="margin-left:20px;">
<%= link_to 'Back', articles_path %>
| <%= link_to 'Edit', edit_article_path(@article) %>
</div>
<br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Blog</title>

    <%= csrf_meta_tags %>
</head>
<body>

<div class="wrapper" style="background-color:grey;height:100%;margin-top:-50px;">
    <div class="container" style="margin-left:300px; margin-top:50px;background-color:white; height:1000px;width:500px;">
        <div class="style" style="margin-left:20px;padding-top:10px;">

        <nav style="margin-left:29%;">
            <h1><a href="http://localhost:3000/articles">Simple Rails Blog</a></h1>
        </nav>
        <hr style="margin-left:-20px;">

        <div style="margin-left:25%;">Username: <i>user</i> Password: <i>secret</i></div>
        <hr style="margin-left:-20px;">

            <%= yield %>
        </div>
    </div>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>